image: maven:latest

cache:
  paths:
    - Back-PI/Back-PI/target

stages:
  - build
  - deploy

build-BackEnd:  
  stage: build
  script:
    - echo "Compiling the code..."
    - cd Back-PI/Back-PI/
    - mvn clean install
    - echo "Compile complete."
  only:
    - BackEnd
  artifacts:
    paths:
      - Back-PI/Back-PI/target/Back-PI.jar

deploy-BackEnd:
  stage: deploy
  image: alpine:3.11
  before_script:
     - apk update && apk add openssh-client bash
     - mkdir -p ~/.ssh
     - eval $(ssh-agent -s)
     - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
     - touch ~/.ssh/config
     - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
     - ssh-keyscan -H $DEPLOY_SERVER_IP >> ~/.ssh/known_hosts

  script:
    - echo "Deploying started..."
    - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl stop Back-PI.service"
   # - scp Back-PI/Back-PI/target/Back-PI.jar ubuntu@$DEPLOY_SERVER_IP:~/grupo-05/Back-PI/Back-PI/target/
    #- ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl start Back-PI.service"
    - echo "Finished deploying the app."
  only:
    - BackEnd
